[package]
name = "fib-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { workspace = true, optional = true }
proc-macros = { path = "proc-macros" }

[features]
pyo3 = ["dep:pyo3"]